[package]
name = "bbe"
version = "0.1.0"
authors = ["darksv <darek969-12@o2.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", rev="9d166f614ba3e70d54a684e3b8f74b1e5b5ee3a3", features = ["image"] }
image = "*"

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3