[package]
name = "bbe"
version = "0.1.0"
authors = ["darksv <darek969-12@o2.pl>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", rev="c6e5a5ed925fbf722af482e168ff1af44c926110", features = ["image"] }
image = "0.23.13"

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3